# -*- coding: utf-8 -*-
"""Copy of dsdo wm9rb qijun

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plW09Q-NmZOHPi548PTwbEtXxDMCL56y
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings('ignore')

"""# 1. Data Loading and Overview"""

import pandas as pd

print("DATA OVERVIEW")

df = pd.read_excel('DSML Individual Coursework Dataset2526.xlsx', sheet_name='Apps')

print("Dataset Shape:", df.shape)

print("Dataset Preview")
display(df.head())

print("Column Information")
summary_table = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Non-Null Count": df.notnull().sum().values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})
display(summary_table)

print("Dataset Summary Statistics")
display(df.describe())

print("Target Variable Check: Rating")
rating_numeric = pd.to_numeric(df["Rating"], errors="coerce")
invalid_ratings = (rating_numeric > 5).sum()
missing_ratings = rating_numeric.isna().sum()

print("Invalid Ratings (>5):", invalid_ratings)
print("Missing Ratings:", missing_ratings)

print("Categorical Cardinality")
cardinality = pd.DataFrame({
    "Column": ["Category", "Content Rating", "Type"],
    "Unique Values": [
        df["Category"].nunique(),
        df["Content Rating"].nunique(),
        df["Type"].nunique()
    ]
})
display(cardinality)

print("Duplicate Rows")
duplicates = df.duplicated().sum()
print("Duplicate Count:", duplicates)

"""# 2. Data Cleaning"""

print("DATA CLEANING")

import pandas as pd
import numpy as np
import re

df_clean = df.copy()

df_clean = df_clean.drop_duplicates().reset_index(drop=True)

df_clean["Rating"] = pd.to_numeric(df_clean["Rating"], errors="coerce")
df_clean = df_clean[(df_clean["Rating"] >= 0) & (df_clean["Rating"] <= 5)]
df_clean = df_clean.dropna(subset=["Rating"])

df_clean["Reviews"] = pd.to_numeric(df_clean["Reviews"], errors="coerce")

df_clean["Installs"] = df_clean["Installs"].astype(str).str.replace("+", "", regex=False)
df_clean["Installs"] = df_clean["Installs"].str.replace(",", "", regex=False)
df_clean["Installs_num"] = pd.to_numeric(df_clean["Installs"], errors="coerce")

df_clean["Price"] = df_clean["Price"].astype(str).str.replace("$", "", regex=False)
df_clean["Price_num"] = pd.to_numeric(df_clean["Price"], errors="coerce")

def extract_android_version(val):
    if pd.isna(val):
        return np.nan
    match = re.search(r'(\d+(\.\d+)?)', str(val))
    return float(match.group(1)) if match else np.nan

df_clean["Android_Version"] = df_clean["Android Ver"].apply(extract_android_version)
categorical_cols = ["Category", "Type", "Content Rating", "Genres"]
for col in categorical_cols:
    df_clean[col] = df_clean[col].astype(str).str.strip()
    df_clean[col] = df_clean[col].replace("nan", np.nan)

print("Cleaned Dataset Preview")
display(df_clean.head())

print("Missing Values After Cleaning")
missing_after = df_clean.isna().sum()
display(missing_after[missing_after > 0])

print("Summary Statistics (Numeric Variables)")
display(df_clean.describe())

print("Final Cleaned Dataset Shape")
print(df_clean.shape)

"""# 3. Feature Engineering"""

print("Feature Engineering")

import numpy as np
import pandas as pd

df_clean['Is_Paid'] = df_clean['Type'].apply(lambda x: 1 if x == 'Paid' else 0)
def price_category(price):
    if pd.isna(price):
        return 'Unknown'
    elif price == 0:
        return 'Free'
    elif price < 5:
        return 'Low'
    else:
        return 'High'
df_clean['Price_Category'] = df_clean['Price_num'].apply(price_category)
def install_level(installs):
    if pd.isna(installs):
        return 'Unknown'
    elif installs < 10000:
        return 'Low'
    elif installs < 1000000:
        return 'Medium'
    else:
        return 'High'
df_clean['Install_Level'] = df_clean['Installs_num'].apply(install_level)
df_clean['Review_Ratio'] = df_clean['Reviews'] / df_clean['Installs_num']
df_clean['Review_Ratio'] = df_clean['Review_Ratio'].replace([np.inf, -np.inf], np.nan)
df_clean['Review_Ratio'] = df_clean['Review_Ratio'].fillna(0)
df_clean['Log_Installs'] = np.log1p(df_clean['Installs_num'])
df_clean['Log_Price'] = np.log1p(df_clean['Price_num'].fillna(0))
def normalize_size(val):
    if pd.isna(val):
        return np.nan
    val_str = str(val).strip().upper()
    if val_str == '' or 'VARIES' in val_str:
        return np.nan
    try:
        if val_str.endswith('M'):
            return float(val_str[:-1]) * 1024
        elif val_str.endswith('K'):
            return float(val_str[:-1])
        else:
            return np.nan
    except:
        return np.nan
df_clean['Size_KB'] = df_clean['Size'].apply(normalize_size)
def size_category(size_kb):
    if pd.isna(size_kb):
        return 'Unknown'
    elif size_kb < 10000:
        return 'Small'
    elif size_kb < 30000:
        return 'Medium'
    else:
        return 'Large'
df_clean['Size_Category'] = df_clean['Size_KB'].apply(size_category)
df_clean['Rating_Class'] = df_clean['Rating'].apply(
    lambda x: 'High' if pd.notna(x) and x >= 4 else ('Low' if pd.notna(x) else np.nan)
)

#-------------------------------------------------------------
print("FEATURE ENGINEERING OUTPUT")
print("1. Preview of engineered features")
display(df_clean[
    [
        'Installs_num',
        'Log_Installs',
        'Price_num',
        'Log_Price',
        'Size_KB',
        'Is_Paid',
        'Price_Category',
        'Install_Level',
        'Size_Category',
        'Review_Ratio',
        'Rating_Class'
    ]
].head())

print("2. Distribution of engineered categorical features")

print("Is_Paid")
display(df_clean['Is_Paid'].value_counts(dropna=False).to_frame(name='Count'))

print("Price_Category")
display(df_clean['Price_Category'].value_counts(dropna=False).to_frame(name='Count'))

print("Install_Level")
display(df_clean['Install_Level'].value_counts(dropna=False).to_frame(name='Count'))

print("Size_Category")
display(df_clean['Size_Category'].value_counts(dropna=False).to_frame(name='Count'))

print("Rating_Class")
display(df_clean['Rating_Class'].value_counts(dropna=False).to_frame(name='Count'))

print("3. Summary statistics of engineered numeric features")
display(
    df_clean[
        ['Installs_num', 'Log_Installs', 'Price_num', 'Log_Price', 'Size_KB', 'Review_Ratio']
    ].describe()
)

print("Feature engineering completed.")

"""# 4. Exploratory Data Analysis (EDA)

"""

print("EDA")

import matplotlib.pyplot as plt
import seaborn as sns

eda_df = df_clean[df_clean['Rating_Class'].notna()].copy()
eda_df = eda_df[eda_df['Install_Level'] != 'Unknown']
eda_df = eda_df[eda_df['Price_Category'] != 'Unknown']
eda_df = eda_df[eda_df['Type'].notna()]
eda_df = eda_df[eda_df['Type'] != 'Unknown']

print("1. Rating Class Distribution")

plt.figure(figsize=(6,4))
sns.countplot(x='Rating_Class', data=eda_df)

plt.title("Rating Class Distribution")
plt.xlabel("Rating Class")
plt.ylabel("Count")

plt.tight_layout()
plt.show()

print("Rating class proportions:")
print(eda_df['Rating_Class'].value_counts(normalize=True).round(4))

print("2. Installs vs Rating")

plt.figure(figsize=(7,5))
sns.boxplot(x='Rating_Class', y='Log_Installs', data=eda_df)

plt.title("Log Installs vs Rating Class")
plt.xlabel("Rating Class")
plt.ylabel("Log Number of Installs")

plt.tight_layout()
plt.show()

print("3. Free vs Paid Apps")

plt.figure(figsize=(6,4))
sns.countplot(x='Type', hue='Rating_Class', data=eda_df)

plt.title("Free vs Paid Apps")
plt.xlabel("App Type")
plt.ylabel("Count")

plt.tight_layout()
plt.show()

print("4. Correlation Heatmap")

plt.figure(figsize=(7,5))
corr = eda_df[['Rating', 'Reviews', 'Installs_num', 'Log_Installs', 'Price_num']].corr()

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")

plt.tight_layout()
plt.show()

print("5. Install Level vs Rating Class")

plt.figure(figsize=(7,5))
sns.countplot(
    x='Install_Level',
    hue='Rating_Class',
    data=eda_df
)

plt.title("Install Level vs Rating Class")
plt.xlabel("Install Level")
plt.ylabel("Count")

plt.tight_layout()
plt.show()

"""# 5. Data Preparation for Modelling and Train-test split"""

print("Data Preparation for Modeling")

df_model = df_clean.copy()

features = [
    'Reviews',
    'Installs_num',
    'Price_num',
    'Size_KB',
    'Log_Installs',
    'Review_Ratio',
    'Is_Paid',
    'Log_Price',
    'Category',
    'Price_Category',
    'Install_Level',
    'Size_Category',
    'Type',
    'Content Rating',
    'Genres',
    'Android_Version'
]

X = df_model[features].copy()
y = df_model['Rating_Class'].copy()

X = X.replace([np.inf, -np.inf], np.nan)

print("Train-Test Split and Encoding")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

numeric_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
for col in numeric_cols:
    median_val = X_train[col].median()
    X_train.loc[:, col] = X_train[col].fillna(median_val)
    X_test.loc[:, col] = X_test[col].fillna(median_val)

categorical_cols = X_train.select_dtypes(include=['object']).columns
for col in categorical_cols:
    mode_val = X_train[col].mode()[0] if not X_train[col].mode().empty else 'Unknown'
    X_train.loc[:, col] = X_train[col].fillna(mode_val)
    X_test.loc[:, col] = X_test[col].fillna(mode_val)

X_train = pd.get_dummies(X_train, drop_first=True)
X_test = pd.get_dummies(X_test, drop_first=True)

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTarget distribution in training set:")
print(y_train.value_counts())

print("\nTarget distribution in test set:")
print(y_test.value_counts())

"""# 6. Logistic Regression (Baseline Model)"""

print("Logistic Regression")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

log_model = LogisticRegression(
    max_iter=1000,
    random_state=42,
    solver='liblinear',
    class_weight='balanced'
)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

high_index = list(log_model.classes_).index('High')
y_prob_log = log_model.predict_proba(X_test)[:, high_index]

log_acc = accuracy_score(y_test, y_pred_log)
log_f1 = f1_score(y_test, y_pred_log, pos_label='High')
log_auc = roc_auc_score((y_test == 'High').astype(int), y_prob_log)

print("Accuracy:", round(log_acc, 4))
print("F1-score:", round(log_f1, 4))
print("ROC_AUC:", round(log_auc, 4))

print("Classification Report:")
print(classification_report(y_test, y_pred_log))

cm = confusion_matrix(y_test, y_pred_log, labels=['Low', 'High'])

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Low', 'High'],
    yticklabels=['Low', 'High']
)

plt.title("Confusion Matrix – Logistic Regression")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

log_eval = pd.DataFrame({
    "Metric": ["Accuracy", "F1-score", "ROC_AUC"],
    "Score": [log_acc, log_f1, log_auc]
}).round(4)

print("Evaluation Table")
display(log_eval)

"""# 7. Logistic Regression Cross-Validation

"""

print("5-Fold Cross-Validation on Training Set: Logistic Regression")

from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import make_scorer, f1_score
import pandas as pd

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

f1_high = make_scorer(f1_score, pos_label='High')

cv_accuracy = cross_val_score(
    log_model,
    X_train,
    y_train,
    cv=cv,
    scoring='accuracy'
)

cv_f1 = cross_val_score(
    log_model,
    X_train,
    y_train,
    cv=cv,
    scoring=f1_high
)

cv_auc = cross_val_score(
    log_model,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

cv_results = pd.DataFrame({
    'Fold': [f'Fold {i}' for i in range(1, 6)],
    'Accuracy': cv_accuracy,
    'F1-score': cv_f1,
    'ROC_AUC': cv_auc
})

mean_row = pd.DataFrame({
    'Fold': ['Mean'],
    'Accuracy': [cv_accuracy.mean()],
    'F1-score': [cv_f1.mean()],
    'ROC_AUC': [cv_auc.mean()]
})

cv_results = pd.concat([cv_results, mean_row], ignore_index=True)

cv_results['Accuracy'] = cv_results['Accuracy'].round(4)
cv_results['F1-score'] = cv_results['F1-score'].round(4)
cv_results['ROC_AUC'] = cv_results['ROC_AUC'].round(4)

print("Cross-Validation Results:")
display(cv_results)

summary = pd.DataFrame({
    'Metric': ['Accuracy', 'F1-score', 'ROC_AUC'],
    'Mean': [cv_accuracy.mean(), cv_f1.mean(), cv_auc.mean()],
    'Std': [cv_accuracy.std(), cv_f1.std(), cv_auc.std()]
})

summary['Mean'] = summary['Mean'].round(4)
summary['Std'] = summary['Std'].round(4)

print("Cross-Validation Summary:")
display(summary)

"""# 8. Random Forest Classifier"""

print("Advanced Model: Random Forest Classifier")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, roc_auc_score, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

high_index = list(rf_model.classes_).index('High')
y_prob_rf = rf_model.predict_proba(X_test)[:, high_index]

rf_acc = accuracy_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf, pos_label='High')
rf_auc = roc_auc_score((y_test == 'High').astype(int), y_prob_rf)

print("Accuracy:", round(rf_acc, 4))
print("F1-score:", round(rf_f1, 4))
print("ROC_AUC:", round(rf_auc, 4))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

cm_rf = confusion_matrix(y_test, y_pred_rf, labels=['Low', 'High'])

plt.figure(figsize=(6,4))
sns.heatmap(
    cm_rf,
    annot=True,
    fmt='d',
    cmap='Greens',
    xticklabels=['Low', 'High'],
    yticklabels=['Low', 'High']
)

plt.title("Confusion Matrix – Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

rf_eval = pd.DataFrame({
    "Metric": ["Accuracy", "F1-score", "ROC_AUC"],
    "Score": [rf_acc, rf_f1, rf_auc]
}).round(4)

print("Evaluation Table")
display(rf_eval)

"""# 9. Random Forest Cross-Validation"""

print("5-Fold Cross-Validation on Training Set: Random Forest")

from sklearn.model_selection import cross_val_score, StratifiedKFold
import pandas as pd

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

rf_cv_accuracy = cross_val_score(
    rf_model,
    X_train,
    y_train,
    cv=cv,
    scoring='accuracy'
)

rf_cv_f1 = cross_val_score(
    rf_model,
    X_train,
    y_train,
    cv=cv,
    scoring='f1'
)

rf_cv_auc = cross_val_score(
    rf_model,
    X_train,
    y_train,
    cv=cv,
    scoring='roc_auc'
)

rf_cv_results = pd.DataFrame({
    'Fold': [f'Fold {i}' for i in range(1, 6)],
    'Accuracy': rf_cv_accuracy,
    'F1-score': rf_cv_f1,
    'ROC_AUC': rf_cv_auc
})

mean_row = pd.DataFrame({
    'Fold': ['Mean'],
    'Accuracy': [rf_cv_accuracy.mean()],
    'F1-score': [rf_cv_f1.mean()],
    'ROC_AUC': [rf_cv_auc.mean()]
})

rf_cv_results = pd.concat([rf_cv_results, mean_row], ignore_index=True)

rf_cv_results['Accuracy'] = rf_cv_results['Accuracy'].round(4)
rf_cv_results['F1-score'] = rf_cv_results['F1-score'].round(4)
rf_cv_results['ROC_AUC'] = rf_cv_results['ROC_AUC'].round(4)

print("Random Forest Cross-Validation Results:")
display(rf_cv_results)

rf_cv_summary = pd.DataFrame({
    'Metric': ['Accuracy', 'F1-score', 'ROC_AUC'],
    'Mean': [
        rf_cv_accuracy.mean(),
        rf_cv_f1.mean(),
        rf_cv_auc.mean()
    ],
    'Std': [
        rf_cv_accuracy.std(),
        rf_cv_f1.std(),
        rf_cv_auc.std()
    ]
}).round(4)

print("Random Forest Cross-Validation Summary:")
display(rf_cv_summary)

"""# 10. Hyperparameter Tuning (GridSearchCV)

"""

print("GridSearchCV Hyperparameter Tuning – Random Forest")

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, roc_auc_score
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

grid_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42, class_weight='balanced'),
    param_grid=param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)

best_rf = grid_rf.best_estimator_
y_pred_best_rf = best_rf.predict(X_test)

high_index = list(best_rf.classes_).index('High')
y_prob_best_rf = best_rf.predict_proba(X_test)[:, high_index]

best_rf_acc = accuracy_score(y_test, y_pred_best_rf)
best_rf_f1 = f1_score(y_test, y_pred_best_rf, pos_label='High')
best_rf_auc = roc_auc_score((y_test == 'High').astype(int), y_prob_best_rf)

best_params_table = pd.DataFrame(
    list(grid_rf.best_params_.items()),
    columns=['Parameter', 'Best Value']
)

tuned_rf_eval = pd.DataFrame({
    'Metric': ['Accuracy', 'F1-score', 'ROC_AUC'],
    'Score': [best_rf_acc, best_rf_f1, best_rf_auc]
}).round(4)

print("1. Best Hyperparameters")
display(best_params_table)

print("2. Best Cross-Validation ROC-AUC")
print(round(grid_rf.best_score_, 4))

print("3. Tuned Random Forest Performance")
display(tuned_rf_eval)

plt.figure(figsize=(6,4))
sns.barplot(data=tuned_rf_eval, x='Metric', y='Score')
plt.title("Performance of Tuned Random Forest")
plt.ylim(0, 1)
plt.ylabel("Score")
plt.xlabel("")
plt.tight_layout()
plt.show()

cm_best_rf = confusion_matrix(y_test, y_pred_best_rf, labels=['Low', 'High'])

plt.figure(figsize=(6,4))
sns.heatmap(
    cm_best_rf,
    annot=True,
    fmt='d',
    cmap='Purples',
    xticklabels=['Low', 'High'],
    yticklabels=['Low', 'High']
)
plt.title("Confusion Matrix – Tuned Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

"""# 11. Feature Importance Analysis

rf
"""

print("Feature Importance – Random Forest")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

rf_importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': rf_model.feature_importances_
})

rf_importance = rf_importance.sort_values(
    by='Importance',
    ascending=False
).reset_index(drop=True)

rf_importance['Importance'] = rf_importance['Importance'].round(4)

print("Top 10 Important Features (Random Forest)")
display(rf_importance.head(10))

top10_rf = rf_importance.head(10).sort_values(by='Importance', ascending=True)

plt.figure(figsize=(8,5))

sns.barplot(
    data=top10_rf,
    x='Importance',
    y='Feature'
)

plt.title("Top 10 Feature Importances – Random Forest")
plt.xlabel("Importance Score")
plt.ylabel("Feature")

plt.tight_layout()
plt.show()

"""tuned rf"""

print("Feature Importance – Tuned Random Forest")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

feature_importance_tuned = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': best_rf.feature_importances_
})

feature_importance_tuned = feature_importance_tuned.sort_values(
    by='Importance',
    ascending=False
).reset_index(drop=True)

feature_importance_tuned['Importance'] = feature_importance_tuned['Importance'].round(4)

top10_tuned = feature_importance_tuned.head(10)

print("Top 10 Most Important Features")
display(top10_tuned.style.hide(axis="index"))

plt.figure(figsize=(10,6))

sns.barplot(
    data=top10_tuned.sort_values(by='Importance'),
    x='Importance',
    y='Feature',
    palette='viridis'
)

plt.title("Top 10 Feature Importances – Tuned Random Forest")
plt.xlabel("Importance Score")
plt.ylabel("Feature")

plt.tight_layout()
plt.show()

"""# 12. Model Comparison"""

print("Final Model Comparison and Summary")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Random Forest',
        'Tuned Random Forest'
    ],
    'Accuracy': [
        log_acc,
        rf_acc,
        best_rf_acc
    ],
    'F1-score': [
        log_f1,
        rf_f1,
        best_rf_f1
    ],
    'ROC_AUC': [
        log_auc,
        rf_auc,
        best_rf_auc
    ]
}).round(4)

print("Model Comparison Table")
display(comparison.style.hide(axis="index"))

comparison_melt = comparison.melt(
    id_vars='Model',
    var_name='Metric',
    value_name='Score'
)

plt.figure(figsize=(9,5))

sns.barplot(
    data=comparison_melt,
    x='Model',
    y='Score',
    hue='Metric'
)

plt.title("Performance Comparison of Classification Models")
plt.ylim(0,1)
plt.xlabel("Model")
plt.ylabel("Score")

plt.legend(title="Metric")

plt.tight_layout()
plt.show()

"""# 13. ROC Curve Comparison"""

print("ROC Curve Comparison: Logistic Regression vs Random Forest vs Tuned Random Forest")

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

# convert target to binary
y_test_binary = (y_test == 'High').astype(int)

# probability of positive class
log_prob = log_model.predict_proba(X_test)[:, list(log_model.classes_).index('High')]
rf_prob = rf_model.predict_proba(X_test)[:, list(rf_model.classes_).index('High')]
tuned_rf_prob = best_rf.predict_proba(X_test)[:, list(best_rf.classes_).index('High')]

# ROC curves
fpr_log, tpr_log, _ = roc_curve(y_test_binary, log_prob)
fpr_rf, tpr_rf, _ = roc_curve(y_test_binary, rf_prob)
fpr_tuned_rf, tpr_tuned_rf, _ = roc_curve(y_test_binary, tuned_rf_prob)

plt.figure(figsize=(7,6))

plt.plot(fpr_log, tpr_log, label=f"Logistic Regression (AUC = {log_auc:.4f})")
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {rf_auc:.4f})")
plt.plot(fpr_tuned_rf, tpr_tuned_rf, label=f"Tuned Random Forest (AUC = {best_rf_auc:.4f})")

plt.plot([0,1],[0,1],'k--', label="Random Classifier")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison of Classification Models")

plt.legend()
plt.tight_layout()
plt.show()

print("ROC Curve Interpretation:")
print(
    "The ROC curves illustrate the classification performance of the three models "
    "across different threshold values. Curves closer to the top-left corner indicate "
    "stronger discrimination between high-rated and low-rated applications."
)

"""# 14. Additional Analysis:Supplementary Regression Benchmark"""

print("Supplementary Regression Analysis")

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

reg_data = df_model.dropna(subset=['Rating']).copy()

X_reg = reg_data[features].copy()
y_reg = reg_data['Rating'].copy()

X_reg = X_reg.replace([np.inf, -np.inf], np.nan)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

numeric_cols_reg = X_train_reg.select_dtypes(include=['int64', 'float64']).columns
categorical_cols_reg = X_train_reg.select_dtypes(include=['object', 'category']).columns

for col in numeric_cols_reg:
    median_val = X_train_reg[col].median()
    X_train_reg.loc[:, col] = X_train_reg[col].fillna(median_val)
    X_test_reg.loc[:, col] = X_test_reg[col].fillna(median_val)

for col in categorical_cols_reg:
    mode_val = X_train_reg[col].mode()[0] if not X_train_reg[col].mode().empty else 'Unknown'
    X_train_reg.loc[:, col] = X_train_reg[col].fillna(mode_val)
    X_test_reg.loc[:, col] = X_test_reg[col].fillna(mode_val)

X_train_reg = pd.get_dummies(X_train_reg, drop_first=True)
X_test_reg = pd.get_dummies(X_test_reg, drop_first=True)
X_train_reg, X_test_reg = X_train_reg.align(X_test_reg, join='left', axis=1, fill_value=0)

param_grid_reg = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2']
}

grid_rf_reg = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=param_grid_reg,
    cv=5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1
)

grid_rf_reg.fit(X_train_reg, y_train_reg)

best_rf_reg = grid_rf_reg.best_estimator_
y_pred_reg = best_rf_reg.predict(X_test_reg)

mae = mean_absolute_error(y_test_reg, y_pred_reg)
rmse = np.sqrt(mean_squared_error(y_test_reg, y_pred_reg))
r2 = r2_score(y_test_reg, y_pred_reg)

reg_summary = pd.DataFrame({
    'Metric': ['MAE', 'RMSE', 'R2'],
    'Score': [mae, rmse, r2]
}).round(4)

best_params_reg = pd.DataFrame(
    list(grid_rf_reg.best_params_.items()),
    columns=['Parameter', 'Best Value']
)

print("Regression Performance")
display(reg_summary.style.hide(axis="index"))

print("Best Hyperparameters")
display(best_params_reg.style.hide(axis="index"))

plt.figure(figsize=(6, 6))
sns.scatterplot(x=y_test_reg, y=y_pred_reg, alpha=0.4)
plt.plot(
    [y_test_reg.min(), y_test_reg.max()],
    [y_test_reg.min(), y_test_reg.max()],
    'r--'
)
plt.xlabel("Actual Rating")
plt.ylabel("Predicted Rating")
plt.title("Actual vs Predicted App Ratings")
plt.tight_layout()
plt.show()

print("Regression Summary")
print(
    f"The tuned Random Forest Regressor achieved MAE = {mae:.4f}, "
    f"RMSE = {rmse:.4f}, and R2 = {r2:.4f}. "
    "Although the regression benchmark provides additional insight into predicting exact rating values, "
    "classification was retained as the primary modelling approach because it is more interpretable "
    "and better aligned with the aim of identifying whether an app is likely to achieve a high rating."
)